### ISSUE TITLE
Display "notes" section in FACTs results

### ISSUE THREAD

**Issue by gadgilrajeev** [gadgilrajeev/BenchmarkingDiffTool#2]
On the individual test page display the notes so that it will be an easier identifier.

**Comment by Sumedh-Patkar** [comment]
Notes section has been displayed on individual tests page.

commit 9916ec28fbf9614253021073a84e6f1e93d0830b
Author: Sumedh Patkar <sumedh.patkar19@gmail.com>
Date:   Mon May 4 12:45:54 2020 -0700
