### ISSUE TITLE
Additional filter options in Bar Graphs for Engineering Team

### ISSUE THREAD

**Issue by gadgilrajeev** [gadgilrajeev/BenchmarkingDiffTool#4]
Add filters to Engineering graph to filter based on single, dual socket etc.

**Comment by Sumedh-Patkar** [comment]
This feature has been added in version **v1.3**

https://github.com/gadgilrajeev/BenchmarkingDiffTool/commit/c13603b60b4950cf73d700119ab6f7401ced568d

**Comment by Sumedh-Patkar** [comment]
This feature has been added in version **v1.3**

Here is the corresponding commit [https://github.com/gadgilrajeev/BenchmarkingDiffTool/commit/c13603b60b4950cf73d700119ab6f7401ced568d](url)
