### ISSUE TITLE
Fixed URLs for dashboards that can be shared

### ISSUE THREAD

**Issue by gadgilrajeev** [gadgilrajeev/BenchmarkingDiffTool#5]
Have a URL for the graphs that are generated as filter labels. This will enable sharing of links

**Comment by Sumedh-Patkar** [comment]
This feature has been added in version **v1.5**

Here is the link to the corresponding commit [https://github.com/gadgilrajeev/BenchmarkingDiffTool/commit/9438da7571ab0a0b2596b581b3fb03c935b09818](url)
