### ISSUE TITLE
Changing reference SKU on workloads with lower is better

### ISSUE THREAD

**Issue by gadgilrajeev** [gadgilrajeev/BenchmarkingDiffTool#6]
Whenever a lower is better score is chosen, then the first time the normalized graphs display correctly. But after the the reference is changed the lower is better variable does not remain persistent.

**Comment by Sumedh-Patkar** [comment]
This issue has been fixed

[https://github.com/gadgilrajeev/BenchmarkingDiffTool/commit/b5e4da9f5dd341eb78c0b475d194403730dfcc91](url)
